spring.application.name=ai-support-assistant
# ===============================
# = Configuration de la base de données PostgreSQL
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/ai-support-assistant
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



server.port=8080
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true


# Google AI Studio Configuration
# ===========================
# ? Configuration Gemini
# ===========================
gemini.api.key=ENV_GOOGLE_API_KEY

gemini.model=gemini-1.5-pro

gemini.base-url=https://generativelanguage.googleapis.com

gemini.api-version=v1beta

gemini.temperature=0.7
gemini.max-tokens=500

gemini.timeout.connect=5000       # délai max de connexion (ms)
gemini.timeout.read=30000         # délai max de lecture (ms)
gemini.timeout.write=10000        # délai max d?écriture (ms)


# Logging
logging.level.com.example.ai_support_assistant=DEBUG

